### ISSUE TITLE
关于预训练模型

### ISSUE THREAD

**Issue by Ann331** [bubbliiiing/retinanet-pytorch#13]
您好，请问有resnet34的预训练模型吗？为什么我使用在其它地方找到的resnet34的预训练模型对网络进行训练，会出现如下报错信息呢：
pretrained_dict = {k: v for k, v in pretrained_dict.items() if np.shape(model_dict[k]) == np.shape(v)}
KeyError: 'conv1.weight'

**Comment by bubbliiiing** [comment]
emm从主干开始就行

**Comment by Ann331** [comment]
> emm从主干开始就行

好的，已经解决了，感谢您的回复。
